execution:
    uuid: 65bfb371-4de5-4c6c-aeb6-4e0a92c97210
    runtime:
        start: 2022-01-04T22:23:55.737713-05:00
        end: 2022-01-04T22:37:59.655510-05:00
        duration: 14 minutes, 3 seconds, and 917797 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:dada2'
    action: denoise_paired
    inputs:
    -   demultiplexed_seqs: 4b755fef-34f7-4680-bd11-315e6e1f1915
    parameters:
    -   trunc_len_f: 190
    -   trunc_len_r: 220
    -   trim_left_f: 0
    -   trim_left_r: 0
    -   max_ee_f: 2.0
    -   max_ee_r: 2.0
    -   trunc_q: 2
    -   min_overlap: 12
    -   pooling_method: independent
    -   chimera_method: consensus
    -   min_fold_parent_over_abundance: 1.0
    -   n_threads: 1
    -   n_reads_learn: 1000000
    -   hashed_feature_ids: true
    output-name: table

transformers:
    inputs:
        demultiplexed_seqs:
        -   from: SingleLanePerSamplePairedEndFastqDirFmt
            to: SingleLanePerSamplePairedEndFastqDirFmt
    output:
    -   from: biom.table:Table
        to: BIOMV210DirFmt
        plugin: !ref 'environment:plugins:types'
        citations:
        - !cite 'view|types:2021.11.0|biom.table:Table|0'
        - !cite 'view|types:2021.11.0|BIOMV210DirFmt|0'

environment:
    platform: linux-x86_64
    python: |-
        3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)
        [GCC 9.4.0]
    framework:
        version: 2021.11.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2021.11.0|0'
    plugins:
        types:
            version: 2021.11.0
            website: https://github.com/qiime2/q2-types
        dada2:
            version: 2021.11.0
            website: http://benjjneb.github.io/dada2/
            citations:
            - !cite 'plugin|dada2:2021.11.0|0'
    python-packages:
        q2-dada2: 2021.11.0
        q2-gneiss: 2021.11.0
        q2-vsearch: 2021.11.0
        q2-diversity: 2021.11.0
        q2-mystery-stew: 2021.11.0
        q2-emperor: 2021.11.0
        qiime2: 2021.11.0
        q2-taxa: 2021.11.0
        q2-fragment-insertion: 2021.11.0
        q2-feature-classifier: 2021.11.0
        q2-longitudinal: 2021.11.0
        q2-composition: 2021.11.0
        q2galaxy: 2021.11.0
        q2-types: 2021.11.0
        q2-quality-control: 2021.11.0
        q2-quality-filter: 2021.11.0
        q2-diversity-lib: 2021.11.0
        q2-metadata: 2021.11.0
        q2cli: 2021.11.0
        q2templates: 2021.11.0
        q2-cutadapt: 2021.11.0
        q2-deblur: 2021.11.0
        q2-phylogeny: 2021.11.0
        q2-alignment: 2021.11.0
        q2-demux: 2021.11.0
        q2-feature-table: 2021.11.0
        q2-sample-classifier: 2021.11.0
        certifi: 2021.10.8
        pytz: '2021.3'
        setuptools: 59.2.0
        cryptography: 35.0.0
        pyzmq: 22.3.0
        pip: 21.3.1
        packaging: '21.3'
        attrs: 21.2.0
        argon2-cffi: 21.1.0
        pyOpenSSL: 21.0.0
        unicodedata2: 13.0.0.post2
        more-itertools: 8.11.0
        Pillow: 8.4.0
        natsort: 8.0.0
        ipython: 7.29.0
        ipywidgets: 7.6.5
        click: 7.1.2
        jupyter-client: 7.1.0
        ipykernel: 6.5.0
        notebook: 6.4.6
        nbconvert: 6.3.0
        pytest: 6.2.5
        tornado: '6.1'
        PyYAML: '6.0'
        PyQt5: 5.12.3
        PyQtWebEngine: 5.12.1
        PyQtChart: '5.12'
        psutil: 5.8.0
        importlib-resources: 5.4.0
        nbformat: 5.1.3
        traitlets: 5.1.1
        tqdm: 4.62.3
        fonttools: 4.28.1
        PyQt5-sip: 4.19.18
        jupyter-core: 4.9.1
        importlib-metadata: 4.8.2
        pexpect: 4.8.0
        lxml: 4.6.4
        DendroPy: 4.5.2
        decorator: 4.4.2
        sepp: 4.3.10
        jsonschema: 4.2.1
        bleach: 4.1.0
        typing-extensions: 4.0.0
        chardet: 4.0.0
        zipp: 3.6.0
        widgetsnbextension: 3.5.2
        matplotlib: 3.5.0
        h5py: 3.3.0
        ijson: 3.1.3
        lz4: 3.1.3
        prompt-toolkit: 3.0.22
        pyparsing: 3.0.6
        Jinja2: 3.0.3
        threadpoolctl: 3.0.0
        requests: 2.25.1
        pycparser: '2.21'
        yq: 2.12.2
        idna: '2.10'
        Pygments: 2.10.0
        python-dateutil: 2.8.2
        networkx: 2.6.3
        bokeh: 2.4.2
        biom-format: 2.1.10
        tzlocal: '2.1'
        MarkupSafe: 2.0.1
        biopython: '1.79'
        urllib3: 1.26.7
        numpy: 1.21.4
        six: 1.16.0
        cffi: 1.15.0
        argcomplete: 1.12.3
        py: 1.11.0
        async-generator: '1.10'
        q2-itsxpress: 1.8.0
        Send2Trash: 1.8.0
        itsxpress: 1.8.0
        scipy: 1.7.2
        PySocks: 1.7.1
        backports.functools-lru-cache: 1.6.4
        cached-property: 1.5.2
        debugpy: 1.5.1
        nest-asyncio: 1.5.1
        pandocfilters: 1.5.0
        nose: 1.3.7
        kiwisolver: 1.3.2
        pandas: 1.2.5
        xopen: 1.2.1
        fastcluster: 1.1.26
        munkres: 1.1.4
        iniconfig: 1.1.1
        deblur: 1.1.0
        bibtexparser: 1.1.0
        joblib: 1.1.0
        emperor: 1.0.3
        msgpack: 1.0.2
        jupyterlab-widgets: 1.0.2
        pluggy: 1.0.0
        numba: 0.53.1
        olefile: '0.46'
        wheel: 0.37.0
        llvmlite: 0.36.0
        Cython: 0.29.24
        scikit-learn: 0.24.1
        unifrac: 0.20.2
        future: 0.18.2
        jedi: 0.18.1
        pyrsistent: 0.18.0
        hdmedians: 0.14.2
        statsmodels: 0.13.1
        CacheControl: 0.12.10
        lockfile: 0.12.2
        terminado: 0.12.1
        xmltodict: 0.12.0
        prometheus-client: 0.12.0
        seaborn: 0.11.2
        isal: 0.11.1
        cycler: 0.11.0
        toml: 0.10.2
        mistune: 0.8.4
        parso: 0.8.2
        pickleshare: 0.7.5
        defusedxml: 0.7.1
        brotlipy: 0.7.0
        ptyprocess: 0.7.0
        dnaio: 0.6.0
        nbclient: 0.5.9
        scikit-bio: 0.5.6
        pynndescent: 0.5.5
        patsy: 0.5.2
        umap-learn: 0.5.2
        webencodings: 0.5.1
        testpath: 0.5.0
        gneiss: 0.4.6
        colorama: 0.4.4
        dill: 0.3.4
        entrypoints: '0.3'
        wcwidth: 0.2.5
        ipython-genutils: 0.2.0
        backcall: 0.2.0
        matplotlib-inline: 0.1.3
        jupyterlab-pygments: 0.1.2
        cutadapt: 0.0.0
